### ISSUE TITLE
Error: optionsNotifier is not a function

### ISSUE THREAD

**Issue by AldoAbdn** [AldoAbdn/Escape-Room-Generator#83]
Uncaught in promise, occurs when verifySignupLong create is called

Error: optionsNotifier is not a function at Object.convert () 
seems to be an issue with featherjs and feather authentication management

**Comment by AldoAbdn** [comment]
Resolved

**Comment by knowsarzehmeh** [comment]
> Resolved

How did you resolve this issue please, i'm experiencing the same issue

**Comment by knowsarzehmeh** [comment]
Resolved....

**Comment by knowsarzehmeh** [comment]
Resolved...passed the notifier(app).notifier instead of passing it as a function
